/*
 * enum.h
 *
 *  Created on: 23/4/2017
 *      Author: utnso
 */

#ifndef HERRAMIENTAS_ENUM_H_
#define HERRAMIENTAS_ENUM_H_

enum{CONSOLA=1,
	KERNEL,
	CPU,
	MEMORIA,
	FS,
	ENVIO_CODIGO,
	DESCONECTARME,
	IMPRIMIR_TEXTO,
	ESPACIO_INSUFICIENTE,
	FINALIZAR_PROGRAMA,
	INICIALIZAR_PROGRAMA,
	ENVIO_PCB,
	DESALOJAR_PROCESO,
	CONTINUAR_EJECUCION,
	WAIT,
	SIGNAL,
	ENTRADA_SALIDA,
	FIN_CPU,
	LECTURA_PAGINA,
	ESCRITURA_PAGINA,
	CAMBIO_PROCESO_ACTIVO,
	TAMANIO_PAGINAS,
	ESPACIO_SUFICIENTE,
	ENVIO_PARTE_PAGINA,
	ENVIO_PAGINA,
	OK,
	MARCOS_INSUFICIENTES,
	PCB,
	EJECUTAR_INSTRUCCION,
	EJECUTAR_ULTIMA_INSTRUCCION,
	ASIGNACION_MEMORIA,
	PROXIMA_INSTRUCCION,
	STACKOVERFLOW,
	GRABAR_VARIABLE_COMPARTIDA,
	VALOR_VARIABLE_COMPARTIDA,
	ESCRIBIR_FD,
	ERROR,
	VALIDAR_ARCHIVO,
	CREAR_ARCHIVO,
	BORRAR,
	OBTENER_DATOS,
	GUARDAR_DATOS,
	DESCONECTAR,
	ABRIR_ANSISOP, /* ANSISOP FUNCION ABRIR*/
	BORRAR_ANSISOP, /* ANSISOP FUNCION BORRAR*/
	CERRAR_ANSISOP, /* ANSISOP FUNCION CERRAR*/
	LIBERAR
	};

#endif /* HERRAMIENTAS_ENUM_H_ */
